---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.3.1
    hajimari:
      title: Apps
      darkTheme: espresso
      alwaysTargetBlank: true
      showGreeting: false
      showAppGroups: false
      showAppStatus: false
      showBookmarkGroups: false
      showGlobalBookmarks: false
      showAppUrls: false
      defaultEnable: true
      namespaceSelector:
        matchNames:
          - default
          - monitoring
          - networking
      customApps:
        - group: Infra
          apps:
            - name: Grafana
              url: https://grafana.${SECRET_DOMAIN}
              icon: simple-icons:grafana
              targetBlank: true
            - name: Prometheus
              url: https://prometheus.${SECRET_DOMAIN}
              icon: simple-icons:prometheus
              targetBlank: true
            - name: Flux
              url: https://flux.${SECRET_DOMAIN}
              icon: simple-icons:sawtooth-wave
              targetBlank: true
            - name: Echo
              url: https://echo.${SECRET_DOMAIN}
              icon: video-input-antenna
              targetBlank: true
            - name: Longhorn
              url: https://longhorn.${SECRET_DOMAIN}
              icon: simple-icons:rancher
              targetBlank: true
    podAnnotations:
      configmap.reloader.stakater.com/reload: hajimari-settings
    persistence:
      data:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 100m
        memory: 128M
