apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:V+pdEg4a5x0wxysDWLFCLGEvleK2pCZf,iv:fVNBDzDyNvuyBGLDrFTu+a+Tc+YIVa2GByZqGrPaqoc=,tag:E1TbU6kCPvwQh+8cR2ZvIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gekefns4nyh2xrkwgll67yt232gl0gndkuq0xrvd8clsjt2gzeas2zryhg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6My9qK2UrUWlOVU8zdkwr
            TE9iKzR5WWJ4elQvMW9FRXc2M3oxUkRBVzBRCmM3WW83Tkp5Zm4yRFQ1SUNjWkZj
            Z2NKUU12cFhWY2FwOVA4K2U0bEZZaDgKLS0tIE9sUEVMNG54Y2dTc0NmSG9HSWdN
            WkVSNnlPV1lJM0k0cWsrdEliSTl0UjQKqjib6wRCiSOuNtsi0c7wpgIw0bkWFgeF
            QVl/6ebv+g7IKaQ12QRK8obgMStQUTf2PD/dtnfTrhB1J8jgclyBQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-19T06:15:38Z"
    mac: ENC[AES256_GCM,data:KZqiTZ7g3efmJJPBJ+m234dmjtssmuAzTFw75JN2WBzMMdT+4H/pG3GRuy6aZ8QOxV9NMt5MkSziVgwMhxd4YpsDxHSluLuP83f8lo2I753mKhjXk6lyLzjxsXXgpL//oN0w1RlwknJEEYKtmardVRRMwiTyOgxpoKKDN2EszuY=,iv:0CbEy3qsZNs0tGwko1L/s+y3rBA6diLHrenE1anTlYI=,tag:QUbYraj1esgJg2Th6Gjbag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
