---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: recyclarr-configmap
    files:
      - recyclarr.yml=./config/recyclarr.yml
