---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: lscr.io/linuxserver/jackett
      tag: v0.21.589
    env:
      TZ: Europe/Paris 
    service:
      main:
        ports:
          http:
            port: 9117
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn
    persistence:
      media:
        enabled: true
        type: nfs
        server: 192.168.10.12
        path: /volume1/test-k8s
        mountPath: /media
        readOnly: true
