apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:x5hi6W9omUxq19SQQQOqZ+ZeQThq5aPvWaWnJ4umo4Y18Bc9NNJ6+tJypdpd0lL3yUrc6k9hE8XMAqKt,iv:XYyqEBv9RUIay1Q/AZGwBlD37WLX37jKxTbV3nx/jqo=,tag:nT3pN6NsdCn7ssNUcEwHXA==,type:str]
    username: ENC[AES256_GCM,data:jjRdVio=,iv:jPhYUvMs8eUixaJ9rvf8AwZR633FMDX7ta2q1GL3jvM=,tag:oY8kSQimHjuYu9PiSeTdfA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gekefns4nyh2xrkwgll67yt232gl0gndkuq0xrvd8clsjt2gzeas2zryhg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRTVOT2xLREoxTVp0TzlX
            b1M1eWJMaFhkVDZxb2lOQ1pQeGhGYjA1a204CnhqZHNsZGpISVI2aUVjcFdsNzBF
            aGh3TE8xUzJ1NjB6ODhoQTNUcnQ1NWsKLS0tIFZrUUF1aUxzaGRNMGpJZVdzL050
            cFpKTGdwNndtdHI5K25Yc2JKSnpHYTgKBtJtMI1AUM5RaRw3IfCU0pEBeSy4+mAB
            sjP6CeNKTnVQxw8UibcdDL8uKLJF4jkWi2PdON543lNni36ISTdvOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-19T06:15:55Z"
    mac: ENC[AES256_GCM,data:RaiXOMFOvSrYvmm7pBI8EBunxvb6A4B3+iTPgxn4q6DU/dgc7KCS8TganLXyOZ7hillHiHb+bnORCiBc27u+DVTt1ofU4UKjNO6plNfXAjdjuhkVhIkX2/18cojEPGMqhijFDKfKO95sITxLXazrrZs2ksTZfvSUMcnib/saPSY=,iv:RCpmqPbFxW9fxfojdQ0dWCmlMvVHhjZzTkRHKgj/ug8=,tag:rshKM8vHVNrxoOw8uus9aw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
