---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: csi-driver-nfs
      namespace: kube-system
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: plexinc/pms-docker
      tag: 1.32.5.7349-8f4248874
    env:
      TZ: Europe/Paris 
      PLEX_CLAIM: "claim-QayJ1vvWk96dY9LspX2m"
    service:
      main:
        ports:
          http:
            port: 32400
    # podSecurityContext:
    #   runAsUser: 568
    #   runAsGroup: 568
    #   fsGroup: 568
    #   fsGroupChangePolicy: OnRootMismatch
    #   supplementalGroups: [44, 105, 10000]
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 20Gi
        storageClass: longhorn
    persistence:
      media:
        enabled: true
        type: nfs
        server: 192.168.10.12
        path: /volume1/test-k8s
        mountPath: /media
        readOnly: true
      transcode:
        enabled: false
      local:
        enabled: true
        type: emptyDir
        mountPath: /.local
